# small_qwen
# default model, other configs will inherit parameters from this unless overridden
model:
  model_name: "Qwen/Qwen2.5-Coder-1.5B-Instruct"
  # only used if run.lora is true
  r: 32
  lora_alpha: 64  # lora paper describes 2x the r
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"