defaults:
  - _self_

run:
  dataset_name: "ASSERT-KTH/Primevul"
  wandb_project: "TTC"
  torch_dtype: "bfloat16"
  train_mode: "lora"

model:
  model_name: "Qwen/Qwen2.5-Coder-1.5B-Instruct"
  load_in_4bit: true
  fast_inference: true
  max_seq_length: 512
  gpu_memory_utilization: 0.6
  max_lora_rank: 32  # Only used if train_mode == "lora"

grpo:
  use_vllm: true
  # Optimizer settings
  learning_rate: 5e-6
  adam_beta1: 0.9
  adam_beta2: 0.99
  weight_decay: 0.1
  warmup_ratio: 0.1
  lr_scheduler_type: "cosine"
  optim: "paged_adamw_8bit"
  
  # Model settings
  bf16: true
  fp16: false
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 2
  
  # Generation settings
  num_generations: 4
  max_prompt_length: 256
  max_completion_length: 256
  
  # Training loop settings
  logging_steps: 1
  max_steps: -1
  save_steps: 250
  max_grad_norm: 0.1
  
  # Logging settings
  report_to: "wandb"
  run_name: "${model.model_name}-GRPO-${run.dataset_name}"
  output_dir: "outputs" 