defaults:
  - model: default
  - grpo: default

run:
  wandb_project: "TTC"
  lora: true
  task_type: "repair"  # "detection" or "repair"
  dataset_type: "stack"  # "primevul" or "stack"
  diff_type: "search_replace"  # "search_replace" or "unified"
  context_lines: 0  # number of context lines to include in diffs
  commit_hash: ""  # will be set automatically
  resume_training: false

hydra:
  job:
    chdir: false  # Prevents Hydra from changing working directory at runtime