defaults:
  - agent: nano
  - _self_

hydra:
  job:
    chdir: false # Prevents Hydra from changing the working directory

# Curation configuration
curation:
  # Dataset configuration
  input_dataset_name: "SWE-Gym/SWE-Gym"
  curation_ratio: 0.25
  dataset_version: "v1.0"
  push_to_hub: false
  
  # Rollout configuration
  num_rollouts_per_problem: 4
  timeout: 120
  max_workers: 4  # ThreadPoolExecutor max workers
  max_problems: null  # Maximum number of problems to process (for testing)
  

agent:
  model: "gemini/gemini-2.5-flash"
  api_base: null
  token_limit: 16384
  tool_limit: 100