defaults:
  - _self_
  - run: repair
  - grpo: single_turn
  - model: small_qwen
  - agent: nano  # not used unless run.task_type is "repo repair"

hydra:
  job:
    chdir: false # Prevents Hydra from changing the working directory