defaults:
  - base_grpo_config
  - _self_

model:
  model_name: "Qwen/Qwen2.5-Coder-7B-Instruct"  # Upgraded to 7B model
  
lora:
  r: 64
  lora_alpha: 128

grpo:
  learning_rate: 3e-6  # Slightly lower learning rate for stability
 
  per_device_train_batch_size: 4  # Reduced batch size to accommodate larger model
  gradient_accumulation_steps: 4  # Increased gradient accumulation to compensate
  
  # Generation settings
  num_generations: 4
  max_prompt_length: 1024    # Increased prompt length
  max_completion_length: 1024  # Increased completion length
