defaults:
  - base_grpo_config
  - _self_

model:
  model_name: "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"  # Upgraded to 7B model
  max_seq_length: 2048  # Increased context length
  gpu_memory_utilization: 0.6  # Decreased memory utilization, more variance with larger sequences and kv caches, TBD
  
lora:
  r: 64
  lora_alpha: 128

grpo:
  learning_rate: 3e-6  # Slightly lower learning rate for stability
 
  per_device_train_batch_size: 4  # Reduced batch size to accommodate larger model
  gradient_accumulation_steps: 4  # Increased gradient accumulation to compensate
  
  # Generation settings
  num_generations: 4
  max_prompt_length: 1024    # Increased prompt length
  max_completion_length: 1024  # Increased completion length
