defaults:
  - _self_
  - model: small_qwen
  - sft: default

# Run configuration (parameters not in SFTConfig)
run:
  wandb_project: "SWE-Gym-SFT"
  dataset_name: "ASSERT-KTH/SWE-Gym-Nano-SFT"
  max_seq_length: 8192
  reward_min: 0.2
  output_model_name: null  # configured in the script
  push_to_hub: true

hydra:
  job:
    chdir: false # Prevents Hydra from changing the working directory 