grpo:
  learning_rate: 3e-6  # Slightly lower learning rate for stability
 
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 4
  
  # Generation settings
  num_generations: 4
  max_prompt_length: 2048
  max_completion_length: 2048
